/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * combinedresult.java
 *
 * Created on 21 Nov, 2016, 3:13:59 PM
 */

package quiz;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author dell
 */
public class combinedresult extends javax.swing.JFrame {

    /** Creates new form combinedresult */
    public combinedresult() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME ", "TOTAL MARKS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);

        jButton1.setText("SHOW RESULT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jButton1)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel m= (DefaultTableModel) jTable1.getModel();
String s4= this.getTitle();
try{
    Class.forName("java.sql.DriverManager");
    Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","aman");
    Statement stm5= con.createStatement();
    String s5=" delete from result ";
    stm5.execute(s5);
    Statement stm1=con.createStatement();
    String s1="Select * from password";
    ResultSet rs=stm1.executeQuery(s1);
    while (rs.next())
    {
        String s2= rs.getString("name");
      Statement stm2=con.createStatement();
    String s3="Select sum( marks ) from "+s2+" ";
    ResultSet rs1= stm2.executeQuery(s3);
    while (rs1.next())
    {   
        String r = rs1.getString(1);
    Statement stm= con.createStatement();
    String s="insert into result values('"+s2+"','"+r+"'); ";
   stm.execute(s);
    }

    }

}
catch(Exception e){
    JOptionPane.showMessageDialog(rootPane, e);

}
try{
    Class.forName("java.sql.DriverManager");
    Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","aman");
    Statement stm= con.createStatement();
    String s="Select * from result ";
    ResultSet rs= stm.executeQuery(s);
    while(rs.next()){
    String a=    rs.getString("name");
    String c=    rs.getString("totalmarks");
    m.addRow(new Object[]{a,c});
    }
}
catch(Exception e){
    JOptionPane.showMessageDialog(rootPane, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new combinedresult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
