/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Nov 15, 2016, 9:04:45 AM
 */

package Shopping;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Applications
 */
public class login_page_anshul extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public login_page_anshul() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 3, 55));
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("ANSHUL-CART");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 10, 440, 60);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 3, 24));
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("To Sign-up. Please Click Here~>>");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 480, 320, 40);

        jLabel4.setFont(new java.awt.Font("Agency FB", 3, 24));
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("Enter Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 300, 220, 40);

        jLabel5.setFont(new java.awt.Font("Agency FB", 3, 24));
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("Enter E-mail Id");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 190, 210, 40);

        jButton1.setFont(new java.awt.Font("Agency FB", 2, 8));
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/login1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 380, 100, 50);

        jButton2.setFont(new java.awt.Font("Agency FB", 2, 24));
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/remove.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 380, 110, 50);

        jButton3.setFont(new java.awt.Font("Agency FB", 2, 24));
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/signup.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 430, 120, 80);

        jTextField1.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 200, 370, 30);

        jPasswordField1.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(260, 310, 370, 30);

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 3, 55));
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Login Page");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 80, 290, 60);

        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/o4YBAFT38QmAVM2JAAM7hR7Bos0098.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String s1= jTextField1.getText();
        try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s2=" select password from password where name = '"+s1+"'";
        ResultSet rs= s.executeQuery(s2);
        while (rs.next())
        {
            String s3 = new String (jPasswordField1.getPassword());
            String nm= rs.getString("password");
            if(s3.equals(nm))
           {
            JFrame o= new men_page1();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();
            }
            else
            {
             JOptionPane.showMessageDialog(rootPane, "invalid password for user '"+s1+"'");
            }
        }
   }
    catch(Exception e)
    {
           JOptionPane.showMessageDialog(rootPane, e);
    }

if(s1.isEmpty())
{
    JOptionPane.showMessageDialog(rootPane, "Sign up your ID");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField1.setText("");
jPasswordField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new signup().setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page_anshul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
