/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * men_shoe_1.java
 *
 * Created on Nov 15, 2016, 12:14:38 PM
 */

package Shopping;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Applications
 */
public class men_shoe_1 extends javax.swing.JFrame {

    /** Creates new form men_shoe_1 */
    public men_shoe_1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 70, 690, 10);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 2, 48));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Shoes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 0, 120, 80);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("6");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(20, 100, 40, 23);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("7");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(20, 140, 40, 23);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("8");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(20, 180, 40, 23);

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("9");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(20, 220, 40, 23);

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("10");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(20, 260, 40, 23);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton7.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15)); // NOI18N
        jButton7.setText("ADD TO CART");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(390, 570, 180, 27);

        jButton1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15)); // NOI18N
        jButton1.setText("ADD TO CART");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 250, 200, 27);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel7.setText("Cillian casual ankle boots");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 490, 260, 22);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel8.setText("Sanko Sneaker");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 180, 160, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(th) Cillian casual ankle boots.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 300, 280, 190);

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel9.setText("Zippy Sneaker");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 180, 150, 22);

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel10.setText("Quebec Sneaker");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(420, 500, 190, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(di0Quebec.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 300, 250, 200);

        jButton3.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15)); // NOI18N
        jButton3.setText("ADD TO CART");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 250, 190, 27);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(150, 210, 110, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(510, 210, 110, 30);

        jButton5.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15)); // NOI18N
        jButton5.setText("ADD TO CART");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(50, 570, 190, 27);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(160, 530, 110, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(480, 530, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(di)Sanko.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 10, 260, 200);

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Price :     Rs.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(360, 520, 120, 40);

        jRadioButton11.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setText("6");
        jPanel1.add(jRadioButton11);
        jRadioButton11.setBounds(10, 320, 40, 23);

        jRadioButton12.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setText("7");
        jPanel1.add(jRadioButton12);
        jRadioButton12.setBounds(10, 360, 40, 23);

        jRadioButton13.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jRadioButton13);
        jRadioButton13.setText("8");
        jPanel1.add(jRadioButton13);
        jRadioButton13.setBounds(10, 400, 40, 23);

        jRadioButton14.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jRadioButton14);
        jRadioButton14.setText("9");
        jPanel1.add(jRadioButton14);
        jRadioButton14.setBounds(10, 440, 40, 23);

        jRadioButton15.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jRadioButton15);
        jRadioButton15.setText("10");
        jPanel1.add(jRadioButton15);
        jRadioButton15.setBounds(10, 480, 40, 23);

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Price :     Rs.");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(370, 210, 120, 40);

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("6");
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(340, 30, 40, 23);

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("7");
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(340, 70, 40, 23);

        jRadioButton8.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText("8");
        jPanel1.add(jRadioButton8);
        jRadioButton8.setBounds(340, 110, 40, 23);

        jRadioButton9.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setText("9");
        jPanel1.add(jRadioButton9);
        jRadioButton9.setBounds(340, 150, 40, 23);

        jRadioButton10.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton10);
        jRadioButton10.setText("10");
        jPanel1.add(jRadioButton10);
        jRadioButton10.setBounds(340, 190, 40, 23);

        jRadioButton16.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jRadioButton16);
        jRadioButton16.setText("6");
        jPanel1.add(jRadioButton16);
        jRadioButton16.setBounds(340, 320, 40, 23);

        jRadioButton17.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jRadioButton17);
        jRadioButton17.setText("7");
        jPanel1.add(jRadioButton17);
        jRadioButton17.setBounds(340, 360, 40, 23);

        jRadioButton18.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jRadioButton18);
        jRadioButton18.setText("8");
        jPanel1.add(jRadioButton18);
        jRadioButton18.setBounds(340, 400, 40, 23);

        jRadioButton19.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jRadioButton19);
        jRadioButton19.setText("9");
        jPanel1.add(jRadioButton19);
        jRadioButton19.setBounds(340, 440, 40, 23);

        jRadioButton20.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jRadioButton20);
        jRadioButton20.setText("10");
        jPanel1.add(jRadioButton20);
        jRadioButton20.setBounds(340, 480, 40, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(di)Zippy.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 20, 260, 170);

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("Price :     Rs.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 200, 120, 40);

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("Price :     Rs.");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 520, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 80, 650, 610);

        jButton10.setBackground(new java.awt.Color(255, 204, 204));
        jButton10.setFont(new java.awt.Font("Andalus", 3, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 153, 153));
        jButton10.setText("Next");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(560, 10, 100, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/pink-background.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 680, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(jRadioButton1.isSelected()== true)
       {
           jTextField2.setText("2999 /-");
       }
       else if(jRadioButton2.isSelected()== true)
       {
           jTextField2.setText("3999 /-");
       }
       else if(jRadioButton3.isSelected()== true)
       {
           jTextField2.setText("4599 /-");
       }
       else if(jRadioButton4.isSelected()== true)
       {
           jTextField2.setText("5999 /-");
       }
        else if(jRadioButton5.isSelected()== true)
       {
           jTextField2.setText("6599 /-");
       }
        String s3=jLabel8.getText();
        String s2= this.getTitle();
        String s4=jTextField2.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into shoe values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(jRadioButton6.isSelected()== true)
       {
           jTextField3.setText("2999 /-");
       }
       else if(jRadioButton7.isSelected()== true)
       {
           jTextField3.setText("3999 /-");
       }
       else if(jRadioButton8.isSelected()== true)
       {
           jTextField3.setText("4599 /-");
       }
       else if(jRadioButton9.isSelected()== true)
       {
           jTextField3.setText("5999 /-");
       }
        else if(jRadioButton10.isSelected()== true)
       {
           jTextField3.setText("6599 /-");
       }
        String s3=jLabel9.getText();
        String s2= this.getTitle();
        String s4=jTextField3.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into shoe values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(jRadioButton11.isSelected()== true)
       {
           jTextField4.setText("2999 /-");
       }
       else if(jRadioButton12.isSelected()== true)
       {
           jTextField4.setText("3999 /-");
       }
       else if(jRadioButton13.isSelected()== true)
       {
           jTextField4.setText("4599 /-");
       }
       else if(jRadioButton14.isSelected()== true)
       {
           jTextField4.setText("5999 /-");
       }
        else if(jRadioButton15.isSelected()== true)
       {
           jTextField4.setText("6599 /-");
       }
        String s3=jLabel7.getText();
        String s2= this.getTitle();
        String s4=jTextField4.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into shoe values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if(jRadioButton16.isSelected()== true)
       {
           jTextField5.setText("2999 /-");
       }
       else if(jRadioButton17.isSelected()== true)
       {
           jTextField5.setText("3999 /-");
       }
       else if(jRadioButton18.isSelected()== true)
       {
           jTextField5.setText("4599 /-");
       }
       else if(jRadioButton19.isSelected()== true)
       {
           jTextField5.setText("5999 /-");
       }
        else if(jRadioButton20.isSelected()== true)
       {
           jTextField5.setText("6599 /-");
       }
        String s3=jLabel10.getText();
        String s2= this.getTitle();
        String s4=jTextField5.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into shoe values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
String s1=this.getTitle();
        JFrame o= new men_shoe_2();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new men_shoe_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
