/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * men_accessories_4.java
 *
 * Created on Nov 15, 2016, 10:16:15 PM
 */

package Shopping;


import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Applications
 */
public class men_accessories_4 extends javax.swing.JFrame {

    /** Creates new form men_accessories_4 */
    public men_accessories_4() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 2, 48));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Accessories");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 0, 220, 80);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton7.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15));
        jButton7.setText("ADD TO CART");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(400, 560, 180, 27);

        jButton3.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15));
        jButton3.setText("ADD TO CART");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(390, 270, 190, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(th)harrison watch.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, -10, 240, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(th)David messenger.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, -20, 310, 200);

        jButton1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15));
        jButton1.setText("ADD TO CART");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 270, 210, 27);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 3, 18));
        jLabel7.setForeground(new java.awt.Color(204, 51, 255));
        jLabel7.setText("Price :     Rs.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 230, 120, 30);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Bookman Old Style", 3, 14));
        jTextField1.setText("4499 /-");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(150, 230, 100, 30);

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 3, 18));
        jLabel8.setForeground(new java.awt.Color(204, 51, 255));
        jLabel8.setText("Price :     Rs.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(340, 230, 120, 30);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Bookman Old Style", 3, 14));
        jTextField2.setText("2499 /-");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(480, 230, 100, 30);

        jButton5.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15));
        jButton5.setText("ADD TO CART");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(30, 570, 190, 27);

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 3, 18));
        jLabel9.setForeground(new java.awt.Color(204, 51, 255));
        jLabel9.setText("Price :     Rs.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 530, 120, 30);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Bookman Old Style", 3, 14));
        jTextField3.setText("699 /-");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(140, 530, 100, 30);

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 3, 18));
        jLabel10.setForeground(new java.awt.Color(204, 51, 255));
        jLabel10.setText("Price :     Rs.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 520, 120, 30);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Bookman Old Style", 3, 14));
        jTextField4.setText("5999 /-");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(490, 520, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(uo)initial ring $6.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 310, 152, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(uo)heartbreaker sunglasses $16.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 320, 150, 180);

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel14.setForeground(new java.awt.Color(204, 102, 255));
        jLabel14.setText("TITAN");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(410, 200, 90, 40);

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel15.setForeground(new java.awt.Color(204, 102, 255));
        jLabel15.setText("DIESEL");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(100, 190, 90, 40);

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel16.setForeground(new java.awt.Color(204, 102, 255));
        jLabel16.setText("Heart Goggles");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(60, 500, 130, 40);

        jLabel17.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel17.setForeground(new java.awt.Color(204, 102, 255));
        jLabel17.setText("'A' Ring");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(420, 490, 90, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 80, 620, 610);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 70, 650, 10);

        jButton9.setBackground(new java.awt.Color(255, 204, 204));
        jButton9.setFont(new java.awt.Font("Andalus", 3, 24));
        jButton9.setForeground(new java.awt.Color(0, 153, 153));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/back.jpg"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(20, 10, 100, 50);

        jButton2.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36));
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 10, 130, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/poYBAFT38QyAaOgGAAK69CcLxxE791.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 650, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String s3=jLabel15.getText();
        String s2= this.getTitle();
        String s4=jTextField1.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into accessories values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
String s1=this.getTitle();
        JFrame o= new men_accessories_3();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();        // TODO add your handling code here:
}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String s3=jLabel14.getText();
        String s2= this.getTitle();
        String s4=jTextField2.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into accessories values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String s3=jLabel16.getText();
        String s2= this.getTitle();
        String s4=jTextField3.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into accessories values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String s3=jLabel17.getText();
        String s2= this.getTitle();
        String s4=jTextField4.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into accessories values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String s1=this.getTitle();
        JFrame o= new men_accessories_2();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new men_accessories_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
