/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * men_page1.java
 *
 * Created on Nov 15, 2016, 9:43:40 AM
 */

package Shopping;

import javax.swing.JFrame;

/**
 *
 * @author Applications
 */
public class men_page1 extends javax.swing.JFrame {

    /** Creates new form men_page1 */
    public men_page1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Batang", 3, 24));
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Top Wear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 30, 180, 60);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Batang", 3, 24));
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Bottom Wear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 10, 210, 60);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Batang", 3, 24));
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Shoes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 110, 180, 60);

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setFont(new java.awt.Font("Batang", 3, 24));
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("Accessories");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(200, 110, 200, 60);

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Andalus", 3, 48));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/exit.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(590, 20, 100, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/SHOP.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 180, 260, 160);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/shop3.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 350, 270, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/shop4.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 360, 220, 170);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/shop2.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 170, 270, 180);

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setFont(new java.awt.Font("Batang", 3, 24));
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("Billing ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(410, 110, 200, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/oYYBAFP1mJaACG7wAAOtvhJXWcY661.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String s1=this.getTitle();
        JFrame o= new men_topwear();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
System.exit(0);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String s1=this.getTitle();
        JFrame o= new men_accessories_1();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String s1=this.getTitle();
        JFrame o= new men_bottom_1();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String s1=this.getTitle();
        JFrame o= new men_shoe_1();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
new billing_section().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new men_page1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
