/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * men_shoe_3.java
 *
 * Created on Nov 15, 2016, 12:14:55 PM
 */

package Shopping;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Applications
 */
public class men_shoe_3 extends javax.swing.JFrame {

    /** Creates new form men_shoe_3 */
    public men_shoe_3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 70, 730, 10);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("6");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(20, 100, 40, 23);

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("9");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(20, 220, 40, 23);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("7");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(20, 140, 40, 23);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("8");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(20, 180, 40, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(th)Stevenson sneaker.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 90, 280, 160);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Shoes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 0, 120, 80);

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("10");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(20, 260, 40, 23);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton7.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15)); // NOI18N
        jButton7.setText("ADD TO CART");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(440, 540, 180, 27);

        jButton1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15)); // NOI18N
        jButton1.setText("ADD TO CART");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 260, 210, 27);

        jButton3.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15)); // NOI18N
        jButton3.setText("ADD TO CART");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 250, 190, 27);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel8.setText("Polka Dot Sneaker");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 450, 200, 22);

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel9.setText("D&G Sneaker");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 470, 200, 22);

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel10.setText("Stevenson Sneaker");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 170, 200, 20);

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel11.setText("Vincent Sneaker");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(490, 180, 200, 22);

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Price :     Rs.");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(410, 480, 120, 40);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(540, 480, 100, 30);

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("Price :     Rs.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(450, 200, 120, 40);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(580, 210, 100, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/2011720325855761 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 290, 260, 170);

        jButton5.setFont(new java.awt.Font("Bradley Hand ITC", 3, 15)); // NOI18N
        jButton5.setText("ADD TO CART");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(30, 550, 190, 27);

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("Price :     Rs.");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 500, 120, 40);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(150, 500, 100, 30);

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("Price :     Rs.");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 200, 120, 40);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(190, 210, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(pu)polka dot sneaker $37.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 300, 250, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/(th)vincent sneaker.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 30, 280, 160);

        jRadioButton11.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("6");
        jPanel1.add(jRadioButton11);
        jRadioButton11.setBounds(10, 310, 40, 23);

        jRadioButton12.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("7");
        jPanel1.add(jRadioButton12);
        jRadioButton12.setBounds(10, 350, 40, 23);

        jRadioButton13.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("8");
        jPanel1.add(jRadioButton13);
        jRadioButton13.setBounds(10, 390, 40, 23);

        jRadioButton14.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("9");
        jPanel1.add(jRadioButton14);
        jRadioButton14.setBounds(10, 430, 40, 23);

        jRadioButton15.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("10");
        jPanel1.add(jRadioButton15);
        jRadioButton15.setBounds(10, 470, 40, 23);

        jRadioButton16.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("6");
        jPanel1.add(jRadioButton16);
        jRadioButton16.setBounds(370, 300, 40, 20);

        jRadioButton17.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton17.setText("7");
        jPanel1.add(jRadioButton17);
        jRadioButton17.setBounds(370, 340, 40, 20);

        jRadioButton18.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton18.setText("8");
        jPanel1.add(jRadioButton18);
        jRadioButton18.setBounds(370, 380, 40, 20);

        jRadioButton19.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton19.setText("9");
        jPanel1.add(jRadioButton19);
        jRadioButton19.setBounds(370, 420, 40, 20);

        jRadioButton20.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton20.setText("10");
        jPanel1.add(jRadioButton20);
        jRadioButton20.setBounds(370, 460, 40, 20);

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("6");
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(370, 30, 40, 23);

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("7");
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(370, 70, 40, 23);

        jRadioButton8.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("8");
        jPanel1.add(jRadioButton8);
        jRadioButton8.setBounds(370, 110, 40, 23);

        jRadioButton9.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("9");
        jPanel1.add(jRadioButton9);
        jRadioButton9.setBounds(370, 150, 40, 23);

        jRadioButton10.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("10");
        jPanel1.add(jRadioButton10);
        jRadioButton10.setBounds(370, 190, 40, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 80, 700, 590);

        jButton9.setBackground(new java.awt.Color(255, 204, 204));
        jButton9.setFont(new java.awt.Font("Andalus", 3, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 153, 153));
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 10, 100, 50);

        jButton10.setBackground(new java.awt.Color(255, 204, 204));
        jButton10.setFont(new java.awt.Font("Andalus", 3, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 153, 153));
        jButton10.setText("Home");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(550, 10, 100, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/pink-background.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 730, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  if(jRadioButton1.isSelected()== true)
       {
           jTextField5.setText("2999 /-");
       }
       else if(jRadioButton2.isSelected()== true)
       {
           jTextField5.setText("3999 /-");
       }
       else if(jRadioButton3.isSelected()== true)
       {
           jTextField5.setText("4599 /-");
       }
       else if(jRadioButton4.isSelected()== true)
       {
           jTextField5.setText("5999 /-");
       }
        else if(jRadioButton5.isSelected()== true)
       {
           jTextField5.setText("6599 /-");
       }
        String s3=jLabel10.getText();
        String s2= this.getTitle();
        String s4=jTextField5.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into shoe values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(jRadioButton6.isSelected()== true)
       {
           jTextField3.setText("2999 /-");
       }
       else if(jRadioButton7.isSelected()== true)
       {
           jTextField3.setText("3999 /-");
       }
       else if(jRadioButton8.isSelected()== true)
       {
           jTextField3.setText("4599 /-");
       }
       else if(jRadioButton9.isSelected()== true)
       {
           jTextField3.setText("5999 /-");
       }
        else if(jRadioButton10.isSelected()== true)
       {
           jTextField3.setText("6599 /-");
       }
        String s3=jLabel11.getText();
        String s2= this.getTitle();
        String s4=jTextField3.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into shoe values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(jRadioButton11.isSelected()== true)
       {
           jTextField4.setText("2999 /-");
       }
       else if(jRadioButton12.isSelected()== true)
       {
           jTextField4.setText("3999 /-");
       }
       else if(jRadioButton13.isSelected()== true)
       {
           jTextField4.setText("4599 /-");
       }
       else if(jRadioButton14.isSelected()== true)
       {
           jTextField4.setText("5999 /-");
       }
        else if(jRadioButton15.isSelected()== true)
       {
           jTextField4.setText("6599 /-");
       }
        String s3=jLabel9.getText();
        String s2= this.getTitle();
        String s4=jTextField4.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into shoe values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if(jRadioButton16.isSelected()== true)
       {
           jTextField2.setText("2999 /-");
       }
       else if(jRadioButton17.isSelected()== true)
       {
           jTextField2.setText("3999 /-");
       }
       else if(jRadioButton18.isSelected()== true)
       {
           jTextField2.setText("4599 /-");
       }
       else if(jRadioButton19.isSelected()== true)
       {
           jTextField2.setText("5999 /-");
       }
        else if(jRadioButton20.isSelected()== true)
       {
           jTextField2.setText("6599 /-");
       }
        String s3=jLabel8.getText();
        String s2= this.getTitle();
        String s4=jTextField2.getText();
                try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
        Statement s= con.createStatement();
        String s1="insert into shoe values('"+s2+"','"+s3+"','"+s4+"' ) ";
        s.execute(s1);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
String s1=this.getTitle();
        JFrame o= new men_shoe_2();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 String s1=this.getTitle();
        JFrame o= new men_page1();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new men_shoe_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
