/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * signup.java
 *
 * Created on Nov 22, 2016, 9:40:29 AM
 */

package Shopping;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author user25
 */
public class signup extends javax.swing.JFrame {

    /** Creates new form signup */
    public signup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Enter your name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 140, 142, 28);

        jLabel2.setFont(new java.awt.Font("French Script MT", 1, 24));
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("City:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 190, 39, 28);

        jLabel3.setFont(new java.awt.Font("French Script MT", 1, 24));
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Phone :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 240, 62, 28);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 240, 210, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 190, 210, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 140, 210, 20);

        jButton1.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/signup.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 410, 120, 70);

        jLabel5.setFont(new java.awt.Font("French Script MT", 1, 24));
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Confirm Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 340, 146, 28);

        jLabel4.setFont(new java.awt.Font("French Script MT", 1, 24));
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 290, 77, 28);

        jPasswordField2.setEchoChar('*');
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(210, 340, 210, 20);

        jPasswordField1.setEchoChar('*');
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(210, 290, 210, 20);

        jLabel6.setFont(new java.awt.Font("Forte", 3, 48));
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Register Here");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 10, 307, 66);

        jButton2.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/login1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 410, 110, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/oYYBAFP1mJaACG7wAAOtvhJXWcY661.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 610, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s1= jTextField1.getText();
        String s2= jTextField2.getText();
        String s3= jTextField3.getText();
        String s4= new String(jPasswordField1.getPassword());
        String s5= new String(jPasswordField2.getPassword());
        
        try {

            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ada","root","a");
            Statement s= con.createStatement();
            String s8=" insert into password values ( '"+s1+"','"+s5+"') ";
            s.execute(s8);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String s1=this.getTitle();
        JFrame o= new login_page_anshul();
            o.setVisible(true);
            o.setTitle(s1);
            this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
